services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Berlin

  matterjs-server:
    image: ghcr.io/matter-js/matterjs-server:latest
    read_only: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - "./matter-data:/data"
    environment:
      TZ: Europe/Berlin
